os: osx
language: objective-c
osx_image: xcode10.2
before_script:
- brew install --HEAD usbmuxd
- brew link usbmuxd
- brew install --HEAD libimobiledevice
- brew install ideviceinstaller ios-deploy
- pod setup
- git clone https://github.com/flutter/flutter.git -b beta
- openssl aes-256-cbc -K $encrypted_fb5c5bbb0f3b_key -iv $encrypted_fb5c5bbb0f3b_iv
  -in build_server_rsa.enc -out build_server_rsa -d
- ssh-add build_server_rsa
- sftp builderfiles@packages.breez.technology:config/conf/lnd.conf conf/lnd.conf
- sftp builderfiles@packages.breez.technology:config/conf/breez.conf conf/breez.conf
script:
- "./flutter/bin/flutter build ios --no-codesign"
cache:
  directories:
  - "$HOME/.pub-cache"
  - "$HOME/Library/Caches/Homebrew"
