os: osx
language: objective-c
osx_image: xcode10.2
before_script:  
  - brew install --HEAD usbmuxd
  - brew link usbmuxd  
  - brew install --HEAD libimobiledevice  
  - brew install ideviceinstaller ios-deploy
  - pod setup
  - git clone https://github.com/flutter/flutter.git -b beta
script:
  - ./flutter/bin/flutter build ios -v --no-codesign
cache:  
  directories:
    - $HOME/.pub-cache
    - $HOME/Library/Caches/Homebrew