os: osx
language: objective-c
osx_image: xcode10.2
addons:
  ssh_known_hosts: packages.breez.technology
before_script:
- eval "$(ssh-agent -s)"
- chmod 600 ./travis/build_server_key
- ssh-add ./travis/build_server_key
- "./travis/add-key.sh"
- brew upgrade go
- go version
- brew install bazaar
- git clone -b lsp https://github.com/breez/breez.git gopath/src/github.com/breez/breez
- export TMP_GOPATH=$(pwd)/gopath
- pushd gopath/src/github.com/breez/breez
- go mod vendor
- export GOPATH=$TMP_GOPATH
- export GO111MODULE=off
- go get golang.org/x/mobile/cmd/gomobile
- go get golang.org/x/mobile/cmd/gobind
- "$GOPATH/bin/gomobile init"
- mkdir -p build/ios
- PATH=$PATH:$GOPATH/bin gomobile bind -target=ios -tags="ios experimental signrpc
  walletrpc chainrpc invoicesrpc routerrpc backuprpc peerrpc submarineswaprpc breezbackuprpc"
  -o build/ios/bindings.framework github.com/breez/breez/bindings
- popd
- brew install --HEAD usbmuxd
- brew link usbmuxd
- brew install --HEAD libimobiledevice
- brew install ideviceinstaller ios-deploy
- pod setup
- git clone https://github.com/flutter/flutter.git -b beta
script:
- mkdir $TRAVIS_BUILD_DIR/conf
- cp -r $GOPATH/src/github.com/breez/breez/build/ios/bindings.framework $TRAVIS_BUILD_DIR/ios/bindings.framework
- sftp builderfiles@packages.breez.technology:config/conf/lnd.conf $TRAVIS_BUILD_DIR/conf/lnd.conf
- sftp builderfiles@packages.breez.technology:config/conf/breez-stg.conf $TRAVIS_BUILD_DIR/conf/breez.conf
- sftp builderfiles@packages.breez.technology:config/conf/marketplace.conf $TRAVIS_BUILD_DIR/conf/marketplace.conf
- sftp builderfiles@packages.breez.technology:config/conf/moonpay.conf $TRAVIS_BUILD_DIR/conf/moonpay.conf
- sftp builderfiles@packages.breez.technology:config/conf/GoogleService-Info.plist
  $TRAVIS_BUILD_DIR/ios/Runner/GoogleService-Info.plist
- "./flutter/bin/flutter upgrade"
- "./flutter/bin/flutter build ios --no-codesign"
after_success:
- travis_wait ./travis/sign.sh
cache:
  directories:
  - "$HOME/.pub-cache"
env:
  global:
  - secure: QZp8VNCEixRL0SxUJMuEpk7WEkUs8nXy44MitvIgW9VZdACL+ncAY+1/XFW/sNZLYtkZufsMFVnVizihcJtcazW8MXcuEU+AVvI12UfZ8MUAEjkdJ+BIfiKY2jg0/NqSpLyfI53z8wmDepCkD1Bta8OnfM3fCWkGw8C7LpidTfASsI1fxW3ykC8y1CyZNmzb2AWWGFSrehL6ukW1yKgK9ppXT8bdc3NPkK1/UfxwbZinx+bqEG7yZ6KmPM6J6f0KuPgWVMQDe1W4ld8+BRR1Bo4iz/v5Tv/NKYZ3jc51WhupCpjIy6harpt+cjgpQht7kNtFSclUq5+lz/+UiWiKmg/uwI0JIbuskXUM6WTgcFNXJilWvUlTVnp0VFPx1edfMAon/cwR/aXpW+ZS6CKMAJIvMyYbvpsXT9PQh1dVPqwGoA83hK9Huds0RwUPOJrZeM5atpxXR4saDgw4iys2mviP6cerAWmVHZlOyTCWitMmrdsCp04w8RwCXQLQcY0381lvYlhibflkWC5DHneQKK277pFOIKthBSJTYXyWzunOyGZVIelh9mPZz7hnP0tyCHvyqlxlLdKSo9CMRnXuL2XDt3UFXg+9jrXpDkGVR3bG2FTPMsmLvFGevaoUJic1nVVKzypDoOGFr9aA+84cu5GCErGxUA+6ZP3jA7RZcvw=
  - secure: nh0DkEsjIbJTWePfrSjQhGGCh7d6Zr/fnkOQmKvcxjAsIt8NXybZJSirto68CSpx9kxh3Pks3jI6L3rMxgWBQ8OJMtAeKkSGgsTyto4DDdSgCUSsa2EewCWxjVCRRvDDpLHThUngXl9EifwVIZihEiJh5pH/7Aq7ngPW0VEXQ7hR5I/FzCVoTUkVEXF8Vb7VhIqeM28KeARNeSYVs+iNcH4S8D8vbLvBtbSYV0pkucjF2EyheCkIIF3Vke/vw1t0Uocwx0NFO/JHxq5O9hJQg9BVNck9nrwuVH0T/65XX5WiJpYl5eMT/SWXuPVChIFWDkKUd1elqim0h0VvHiJqpJMfwKtwg78spALHpjagfoyL8Kj3Ewwi0pzNb6btpjKyQQvk84QDk1xXFSmZ/U5dAiM554q1Vm29kBwo5hdYJgC/SmUb9yNlQ1u+a2rj/Ii9N3k4vvw4ZP1jswZt1ICGSrFNR3hQhv6tu8trvPBKOf6hWYzlJP8Pzo2C/YdoNXLer0s4IQ7cbsP+tvFsYBgY/jMBHlI+LmfUrA+DhR3fgOGt79f48fDosA4bK8IrtWtnCyLQQRTstuFsBt6kCbBhPP9dV0lmTB5Vw+cNYi1GKs2pmRRSzr7QJ+Vnl17QqdEW+MQ71+/GVqGo+y3s4kntO7F4C7LNl+5CtsmGIrmp7bM=
  - secure: HZLmiqkgBb5fua16fq442+r8q1xwB9HVw35DfGXznBs93tyO2UZTu3HWFw3A+DoP0nL16m2CCmcR9hoX7taJTvMn1Tj67Vgwc8bf+1EArihP43eoOJK6PxEU9y8ARJ3fAfrsu3mPk5zLFb+UVaNVa/YLyJyikF4ihEvFexYQrLuk4ocM0jXH6oAi34crZBWRIpk+0EGhsZ1GHs33qAl0QsxSpFNgn289o+0M8hFXY+c7xrt93BO27t3zS34YJYvHsKwo/ouHI3wcCOciAbAhUmCIbWxO3UDLdqyBaER3GyqptW9zjBnIJoQssE8jatabqqkJeZ3kmQAjC9jTQ03x4kGCy/0FL1o9UGBMjjd2jjXTLaghUoRydAIqOfmho6wUmCZvImpVTPO6mY+cr/fog93YD3mh99nck1gdAQucFd50NpU3N09dXXtpuDJPwyo46AcvVUtJJJ0LgVFLEvVKD6NO4qeMcxC6UXpvcdhk6gTvuAuuZn17U/ubGl8hjiu94a7lFB/0wuZXBnSvFc1YGr5p+9JqI6bSNsYmyZ72iu99+JCZBrJfssMs/5Nl0J3YWP0zJ6Wby07ZfL+ivemxyu5RsjkQrU+hBjEKhzmtUS32CnzqdK/fd8FiKUqd3sRSr2rheQrkY/c+lpUkGHNYRykMt6lINyvydyeA8YvHXsM=
  - secure: rpvTrvSBfMY817e1cw1azlGH2lQ9IAbNDN4JpxMfwdtrmMtYB9F9IvPQgCy8irwILdgdSqVrht1G8sLoF9dZoZSc3mfqOEoThxkM4fzChQzh2YMc08/d+lvUVBdhC+YgujKPbEhqrzcpkarmWwYBi30LKQU/c6ps2KvGklcDh25fuCWIkrB7PwBD4f4fRvMHqxVAl37O3q/8b+VbBnrp8PwdzxxnKDm21BnCGWbwVchigAtvetvIiWkY73p2ASgBNO00z+6+ZwwC/LA0JKp7+h9lxjAdpwPkI7gc6Zisv2+9TXBztXJXJJ3KPJzpK5S9xyONSuiVK2JYWf3o2X5b9Dut3TmL6pR+ohviUVe1AzdR1p0ESlWVqFaaRhAr/uHRFVMQg7RYcPuureYCwR67ClheiHxIv5rDNMWKuDdTJOnzgBOXSnVE0Fs0k3Kz9FyJ1fgT5eyKKJmjW5xyXcjPheK/0TYLmuZL9+/VBptV4wKe6X71tYt0ZOMhjrRTJVz3G17iMjWxhrArwQL0EXK20egcYFmilpZAEsxzgz9bjfTVY6mU6fj//1iGPK3uEt/BK5PathnKi/i94eYLz26ey8fFlVISxv5HDr6eLrJWpvET8MI8S4858lWyawi8SjXvLN0piXGrzh5hi3W23NXJiW2IiViwpQGbpZBKzX/dcoE=
  - secure: ZMIocr2DKGiqspXRqmBYN8OkcMlqchPExFEHIyqMPs8iMtogAat3lYRZgTHRh7t/QYDxJqPSFyKc6vqFfYYA8RrdAJ7jknUWU31oXb+qqAYLaRON61WrjMasCRTqHn1pBrSpegiyr+BgMn+JLU0GnTODDymZNpVbQGnzx4TRh8RFpyNSf6RRv3IfzWeAEQLgBt0MGCeEQo6n/Hz5Joxw0Vg1abaXL/0Pu/NX/Jptq54eNKjADs0Q7w2p4QNay8pFjiqG+m7K/pfR6+jE53PJDhZLseb+M/27pClR7PrzQUHIdRqw6U668M4U10RMk91F2cbtDfwPvTRosvJrppklvtKdeezTZ80W442IZ1tfcJ2S0uaaReTNo4cRmrbQxiR3jgZ0He0couGxCsO7tP8g4cZYOkdlAR+th+bP8jbm1RyTInSCQgb4erIrX681/X+vpJlYZUYung0SiTQGExZoGpemcPbNGDgZn+W5KvJg1LXJiBH+gBFdh1UdftjhhMdZogQAs23X5s/O/LdmThg2nBIPdBBHZtf00tJlNT13WYMjEHbxz0PXR2dSRq9tUfxuThyOqX+y3/HpR36EnOqZzfNDufOXI/15ZUCPoqBwCk3rNnsKmNBUKZNbeBFFn6i88YjEU5xpoIILVNKR2whyQakCZqTMB9joubvtadY53J0=
  - secure: wapH1TWZWu5Q8aa+JFOhG3cWIFA6D05WYcLvPfUXQb+u5ILFACJ1DBtlcBv9LrKHUG6CKj0HbDgjLiHx2Vjsw793iiRz07UgiytlBJGETGgt6Q6RpwYyboZUwiH/S6v3iaSk8jgqWf7SMPMAFHg8GlFqJtnrcovDhXyQfNfUaVKqT9tmL3RRgLf/vt/DJtf9WXpn1sVC1OT75rexqlKPedCUqRAAlzxLe9CIM9/hEPST572Kme/n1zIjfpLb5VydKcP+gPfB3hwV508RhXbxVvhBJy8RuTOHXqdaRFh6u+vNS4E2HrhWOxA8MLMoSNopL5opjX0UYFjpRyYZypg8fjkBggOWyhTpjKQJV4cW+0dnSeocFYvk9SS6wpZUBLtctgrBUBNZ4zP8j8A3YXt3uCPVTIeZ9EvtqUkmKPBjQUwDwzhOdJs0PlupN2q+zPHuUaggqeZVgxfhva1nmS5GEjmOhCDhHOFI3lYh3SMagc95onafhLzzQP17HhBbdNSZVSYA/iwaOqfyS9vOk5DkJU1awS5K2c/8R6+/BClBdWH+EFVsADPUM5jwJD0/chOysytbWxKyu8Z6w+9UINaL1EBOaGlRQ2Tb4RXi6HM/7YXG1WrSoQDE98D1t05ljyrcCLchI/V0ZwPeqIM7PqjGGdTIFEM6W3iWE7lKsXXDXps=
  - secure: B8GQZ5Nvp9PKTFnvCx2joGJNEjQECovvBFHJmRZX4xVUe4hsGgn9WUJurarbLbVbsX4OkLj6RyO+Zx0XAwO6b9zEO3LpshM1M+CbK3f7gWb2x6CuALc6GXi/P8sur7IE4qDggCxtjFSLKH+2pN162tNVmIviAVnA/W2h4xMFs1s6pewbX7v4i1nBYQnflQ9jrAWwWnYJYR/DJFXSsgmonHsNSc63HW7Spq+e0eKI8SPHTOIhBQp6pJ3gdozCNvl73zFbJQVdiagJls12sbx9tuJ0naoCkqgHg1ZGmtMSMgKPMGUrT1YWruJEe4mVe+rF/jKFnXKMJP6S6sStkZTns2BG8n6tWung5V1MHGl8bfkblfXr8IhORIzYX43QQaEpi2NnVaQlogYXoAENqNvoV90uj0nJ115ShELXC2l6D2pD4bQ30Beo5rDskPD2jz5G5HjlR7SWaQvRrlVaUPbWw9Vj4/pamROrKrcabufUPDf+z58ICr18F8E6iH3dZ/d0rmhpOKOk45s5FgxAgZ7nFj3wrUogiERRN6VupDLyoxazQk89IacbeTrenuEqwjrB0ASq3dtPPDDJK/WdkSf66L/dsSssAZsRVlI+VJgdGdH0fMzWxpMna6yxFr96jw7WP8Sc7wc1w9bPLA4eOp8Ogj9wiAUCqlSdms85JoVDW/s=
before_install:
- openssl aes-256-cbc -K $encrypted_fb5c5bbb0f3b_key -iv $encrypted_fb5c5bbb0f3b_iv
  -in build_server_key.enc -out ./travis/build_server_key -d
