os: osx
language: objective-c
osx_image: xcode10.2
addons:
  ssh_known_hosts: packages.breez.technology
before_script:
- openssl aes-256-cbc -K $encrypted_fb5c5bbb0f3b_key -iv $encrypted_fb5c5bbb0f3b_iv
  -in build_server_rsa.enc -out build_server_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 build_server_rsa
- ssh-add build_server_rsa
- sftp builderfiles@packages.breez.technology:config/conf/lnd.conf $TRAVIS_BUILD_DIR/conf/lnd.conf
- sftp builderfiles@packages.breez.technology:config/conf/breez.conf $TRAVIS_BUILD_DIR/conf/breez.conf
- brew install --HEAD usbmuxd
- brew link usbmuxd
- brew install --HEAD libimobiledevice
- brew install ideviceinstaller ios-deploy
- pod setup
- git clone https://github.com/flutter/flutter.git -b beta
script:
- "./flutter/bin/flutter build ios --no-codesign"
cache:
  directories:
  - "$HOME/.pub-cache"  
