name: breez
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  grpc: ^1.0.1
  protobuf: ^1.0.1
  flutter_slidable: ^0.5.4
  path_provider: any
  firebase_core: 0.4.0+3
  firebase_database: ^3.0.0
  firebase_messaging: ^5.0.1+1
  firebase_dynamic_links: ^0.5.0
  shared_preferences: ^0.5.1+2
  share_extend:
    git:
      url: https://github.com/breez/ShareExtend.git
  qr_flutter: ^2.0.0
  hex: "^0.1.1"
  rxdart: "^0.18.1"
  flutter_advanced_networkimage: 0.6.0-alpha.1
  intl: ^0.15.7
  flushbar: ^1.3.0
  barcode_scan: ^1.0.0
  image_picker: ^0.5.0+9
  image: any
  package_info: ^0.4.0+13
  uuid: ^1.0.3
  ini: ^2.0.1
  connectivity: ^0.4.5+3
  logging: ^0.11.3+2
  flutter_svg: "^0.14.2"
  json_annotation: ^2.0.0
  http: ^0.12.0+1
  url_launcher: ^5.0.1
  archive: ^2.0.8
  duration: ^2.0.8
  dio: ^2.1.13
  sqflite: ^1.2.1
  badges: ^1.1.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  image_cropper: ^1.1.1
  uni_links: ^0.2.0
  flutter_webview_plugin:
    git:
      url: https://github.com/breez/flutter_webview_plugin.git
  keyboard_actions: ^2.1.1
  flutter_secure_storage: ^3.2.1+1
  auto_size_text: 2.0.2+1
  app_settings: ^1.0.6+2
  bip39: ^1.0.3
  crypto: ^2.1.2
  flutter_typeahead:
    git:
      url: https://github.com/breez/flutter_typeahead.git
  csv: ^4.0.3
  local_auth:
    git:
      url: https://github.com/breez/local_auth.git

dev_dependencies:
  mockito: "^3.0.0"
  protoc_plugin: ^19.0.1
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_test:
    sdk: flutter
  test: ^1.5.1


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - cert/letsencrypt.cert
    - conf/lnd.conf
    - conf/breez.conf
    - conf/marketplace.conf
    - conf/moonpay.conf
    - src/json/
    - src/images/
    - src/icon/
    - src/icon/animals/
    - src/icon/vendors/
    - src/animations/welcome/
    - src/scripts/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: IBMPlexSansRegular
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
    - family: IBMPlexSansMedium
      fonts:
        - asset: fonts/IBMPlexSans-Medium.ttf
    - family: IBMPlexSansLight
      fonts:
        - asset: fonts/IBMPlexSans-Light.ttf
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: animals
      fonts:
        - asset: fonts/animals.ttf
    - family: Breez Logo
      fonts:
        - asset: fonts/breezlogo.ttf
    - family: ComfortaaBold
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
    - family: SAT
      fonts:
        - asset: fonts/sat.otf
