name: breez
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter
  grpc: ^1.0.1
  protobuf: any

  path_provider: any
  firebase_core: 0.4.0+3
  firebase_database: ^3.0.0
  firebase_messaging: ^5.0.1+1
  firebase_dynamic_links:
    git:
      url: https://github.com/breez/plugins.git
      ref: running_app_link
      path: packages/firebase_dynamic_links
  shared_preferences: ^0.5.1+2
  share_extend:
    git:
      url: https://github.com/breez/ShareExtend.git
  qr_flutter: ^2.0.0  
  hex: "^0.1.1"
  rxdart: "^0.18.1"  
  flutter_advanced_networkimage: any
  intl: ^0.15.7
  flushbar: ^1.3.0
  barcode_scan:
    git:
       url: https://github.com/breez/flutter_barcode_reader.git  
       ref: ios
  image_picker: ^0.5.0+9
  image: any
  package_info: any  
  uuid: ^1.0.3
  ini: ^2.0.1
  connectivity: ^0.4.2
  logging: ^0.11.3+2
  auto_size_text: ^0.2.1
  flutter_svg: "^0.13.0"
  json_annotation: ^2.0.0
  http: ^0.12.0+1
  url_launcher: ^5.0.1
  archive: ^2.0.8
  duration: ^2.0.8
  #simple_share: ^0.0.1+4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  image_cropper: ^1.0.2
  uni_links: ^0.2.0
  flutter_webview_plugin:
    git:
      url: https://github.com/breez/flutter_webview_plugin.git
  keyboard_actions: ^2.1.1
  flutter_secure_storage: ^3.2.1+1

dev_dependencies:
  mockito: "^3.0.0"
  protoc_plugin: ^16.0.1
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_test:
    sdk: flutter
  test: ^1.5.1


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - cert/letsencrypt.cert
    - conf/lnd.conf
    - conf/breez.conf
    - conf/marketplace.conf
    - src/json/
    - src/images/
    - src/icon/
    - src/icon/animals/
    - src/icon/vendors/
    - src/animations/welcome/
    - src/scripts/

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
    - family: IBMPlexSansRegular
      fonts:
        - asset: fonts/IBMPlexSans-Regular.ttf
    - family: IBMPlexSansMedium
      fonts:
        - asset: fonts/IBMPlexSans-Medium.ttf
    - family: IBMPlexSansLight
      fonts:
        - asset: fonts/IBMPlexSans-Light.ttf
    - family: icomoon
      fonts:
        - asset: fonts/icomoon.ttf
    - family: animals
      fonts:
        - asset: fonts/animals.ttf
    - family: Breez Logo
      fonts:
        - asset: fonts/breezlogo.ttf
    - family: ComfortaaBold
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
